name: Python Scheduled Script

on:
  # Triggers the workflow every 6 hours
  schedule:
    - cron: "10 */6 * * *"
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
      
      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute Python Script
        run: python ralphscan.py
